# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import ai_service_pb2 as ai__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ai_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AiServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SuggestAssignment = channel.unary_unary(
                '/ai.AiService/SuggestAssignment',
                request_serializer=ai__service__pb2.SuggestAssignmentRequest.SerializeToString,
                response_deserializer=ai__service__pb2.SuggestAssignmentResponse.FromString,
                _registered_method=True)
        self.ApproveSuggestion = channel.unary_unary(
                '/ai.AiService/ApproveSuggestion',
                request_serializer=ai__service__pb2.ApproveSuggestionRequest.SerializeToString,
                response_deserializer=ai__service__pb2.ApproveSuggestionResponse.FromString,
                _registered_method=True)
        self.GradeAssignment = channel.unary_unary(
                '/ai.AiService/GradeAssignment',
                request_serializer=ai__service__pb2.GradeAssignmentRequest.SerializeToString,
                response_deserializer=ai__service__pb2.GradeAssignmentResponse.FromString,
                _registered_method=True)
        self.GeneratePerformanceReport = channel.unary_unary(
                '/ai.AiService/GeneratePerformanceReport',
                request_serializer=ai__service__pb2.GeneratePerformanceReportRequest.SerializeToString,
                response_deserializer=ai__service__pb2.GeneratePerformanceReportResponse.FromString,
                _registered_method=True)


class AiServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SuggestAssignment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApproveSuggestion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GradeAssignment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GeneratePerformanceReport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AiServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SuggestAssignment': grpc.unary_unary_rpc_method_handler(
                    servicer.SuggestAssignment,
                    request_deserializer=ai__service__pb2.SuggestAssignmentRequest.FromString,
                    response_serializer=ai__service__pb2.SuggestAssignmentResponse.SerializeToString,
            ),
            'ApproveSuggestion': grpc.unary_unary_rpc_method_handler(
                    servicer.ApproveSuggestion,
                    request_deserializer=ai__service__pb2.ApproveSuggestionRequest.FromString,
                    response_serializer=ai__service__pb2.ApproveSuggestionResponse.SerializeToString,
            ),
            'GradeAssignment': grpc.unary_unary_rpc_method_handler(
                    servicer.GradeAssignment,
                    request_deserializer=ai__service__pb2.GradeAssignmentRequest.FromString,
                    response_serializer=ai__service__pb2.GradeAssignmentResponse.SerializeToString,
            ),
            'GeneratePerformanceReport': grpc.unary_unary_rpc_method_handler(
                    servicer.GeneratePerformanceReport,
                    request_deserializer=ai__service__pb2.GeneratePerformanceReportRequest.FromString,
                    response_serializer=ai__service__pb2.GeneratePerformanceReportResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai.AiService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai.AiService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AiService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SuggestAssignment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.AiService/SuggestAssignment',
            ai__service__pb2.SuggestAssignmentRequest.SerializeToString,
            ai__service__pb2.SuggestAssignmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApproveSuggestion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.AiService/ApproveSuggestion',
            ai__service__pb2.ApproveSuggestionRequest.SerializeToString,
            ai__service__pb2.ApproveSuggestionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GradeAssignment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.AiService/GradeAssignment',
            ai__service__pb2.GradeAssignmentRequest.SerializeToString,
            ai__service__pb2.GradeAssignmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GeneratePerformanceReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.AiService/GeneratePerformanceReport',
            ai__service__pb2.GeneratePerformanceReportRequest.SerializeToString,
            ai__service__pb2.GeneratePerformanceReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
