"""
db/queries/conversations.py

Raw asyncpg queries for the conversations and messages tables.
No ORM -- plain SQL, typed return values.

All UUIDs are generated by PostgreSQL (gen_random_uuid()).
The app never generates IDs.
"""

from __future__ import annotations

import logging
from typing import Any

from db.pool import get_pool

logger = logging.getLogger(__name__)


async def create_conversation(
    session_id: str,
    user_id: str,
    workspace_id: str | None,
) -> str:
    pool = get_pool()
    row = await pool.fetchrow(
        """
        INSERT INTO conversations (session_id, user_id, workspace_id, started_at, last_active_at)
        VALUES ($1::uuid, $2::uuid, $3::uuid, NOW(), NOW())
        RETURNING id::text
        """,
        session_id,
        user_id,
        workspace_id,
    )
    conversation_id: str = row["id"]
    logger.debug("Created conversation: %s", conversation_id)
    return conversation_id


async def get_conversation_by_id(conversation_id: str) -> dict[str, Any] | None:
    pool = get_pool()
    row = await pool.fetchrow(
        """
        SELECT
            id::text,
            session_id::text,
            user_id::text,
            workspace_id::text,
            started_at,
            last_active_at
        FROM conversations
        WHERE id = $1::uuid
        """,
        conversation_id,
    )
    return dict(row) if row else None


async def touch_conversation(conversation_id: str) -> None:
    await get_pool().execute(
        "UPDATE conversations SET last_active_at = NOW() WHERE id = $1::uuid",
        conversation_id,
    )


async def append_message(
    conversation_id: str,
    role: str,
    content: str,
    blocks: dict | list | None = None,
    tokens_used: int | None = None,
) -> str:
    import json

    pool = get_pool()
    blocks_json = json.dumps(blocks) if blocks is not None else None

    row = await pool.fetchrow(
        """
        INSERT INTO messages (conversation_id, role, content, blocks, tokens_used, created_at)
        VALUES ($1::uuid, $2::message_role, $3, $4::jsonb, $5, NOW())
        RETURNING id::text
        """,
        conversation_id,
        role,
        content,
        blocks_json,
        tokens_used,
    )
    message_id: str = row["id"]

    await touch_conversation(conversation_id)

    logger.debug("Appended message: %s role=%s conversation=%s", message_id, role, conversation_id)
    return message_id


async def load_message_history(
    conversation_id: str,
    limit: int,
) -> list[dict[str, Any]]:
    import json

    pool = get_pool()
    rows = await pool.fetch(
        """
        SELECT
            id::text,
            role::text,
            content,
            blocks,
            tokens_used,
            created_at
        FROM messages
        WHERE conversation_id = $1::uuid
          AND role IN ('user', 'assistant')
        ORDER BY created_at DESC
        LIMIT $2
        """,
        conversation_id,
        limit,
    )

    messages = []
    for row in reversed(rows):
        record = dict(row)
        if record["blocks"] and isinstance(record["blocks"], str):
            record["blocks"] = json.loads(record["blocks"])
        messages.append(record)

    return messages
