"""
db/queries/conversations.py

Raw asyncpg queries for the conversations and messages tables.
No ORM -- plain SQL, typed return values.

All UUIDs are generated by PostgreSQL (gen_random_uuid()).
The app never generates IDs.
"""

from __future__ import annotations

import logging
from typing import Any

from db.pool import get_pool

logger = logging.getLogger(__name__)


async def create_conversation(
    session_id: str,
    user_id: str,
    conversation_type: str = "chat",
) -> str:
    pool = get_pool()
    row = await pool.fetchrow(
        """
        INSERT INTO conversations (session_id, user_id, type, started_at, last_active_at)
        VALUES ($1::uuid, $2::uuid, $3, NOW(), NOW())
        RETURNING id::text
        """,
        session_id,
        user_id,
        conversation_type,
    )
    conversation_id: str = row["id"]
    logger.debug("Created conversation: %s type=%s", conversation_id, conversation_type)
    return conversation_id


async def get_conversation_by_id(conversation_id: str) -> dict[str, Any] | None:
    pool = get_pool()
    row = await pool.fetchrow(
        """
        SELECT
            id::text,
            session_id::text,
            user_id::text,
            workspace_id::text,
            started_at,
            last_active_at
        FROM conversations
        WHERE id = $1::uuid
        """,
        conversation_id,
    )
    return dict(row) if row else None


async def get_conversation_by_session_id(session_id: str) -> dict[str, Any] | None:
    pool = get_pool()
    row = await pool.fetchrow(
        """
        SELECT
            id::text,
            session_id::text,
            user_id::text,
            workspace_id::text,
            type,
            started_at,
            last_active_at
        FROM conversations
        WHERE session_id = $1::uuid
        ORDER BY started_at DESC
        LIMIT 1
        """,
        session_id,
    )
    return dict(row) if row else None


async def touch_conversation(conversation_id: str) -> None:
    await get_pool().execute(
        "UPDATE conversations SET last_active_at = NOW() WHERE id = $1::uuid",
        conversation_id,
    )


async def list_conversations_by_user(user_id: str, limit: int = 20, conversation_type: str | None = None) -> list[dict[str, Any]]:
    pool = get_pool()
    if conversation_type:
        rows = await pool.fetch(
            """
            SELECT
                c.id::text,
                c.session_id::text,
                c.user_id::text,
                c.type,
                c.started_at,
                c.last_active_at,
                (SELECT content FROM messages WHERE conversation_id = c.id ORDER BY created_at ASC LIMIT 1) AS first_message,
                (SELECT content FROM messages WHERE conversation_id = c.id ORDER BY created_at DESC LIMIT 1) AS last_message
            FROM conversations c
            WHERE c.user_id = $1::uuid AND c.type = $3
            ORDER BY c.last_active_at DESC
            LIMIT $2
            """,
            user_id,
            limit,
            conversation_type,
        )
    else:
        rows = await pool.fetch(
            """
            SELECT
                c.id::text,
                c.session_id::text,
                c.user_id::text,
                c.type,
                c.started_at,
                c.last_active_at,
                (SELECT content FROM messages WHERE conversation_id = c.id ORDER BY created_at ASC LIMIT 1) AS first_message,
                (SELECT content FROM messages WHERE conversation_id = c.id ORDER BY created_at DESC LIMIT 1) AS last_message
            FROM conversations c
            WHERE c.user_id = $1::uuid
            ORDER BY c.last_active_at DESC
            LIMIT $2
            """,
            user_id,
            limit,
        )
    return [dict(r) for r in rows]


async def append_message(
    conversation_id: str,
    role: str,
    content: str,
    blocks: dict | list | None = None,
    tokens_used: int | None = None,
) -> str:
    import json

    pool = get_pool()
    blocks_json = json.dumps(blocks) if blocks is not None else None

    row = await pool.fetchrow(
        """
        INSERT INTO messages (conversation_id, role, content, blocks, tokens_used, created_at)
        VALUES ($1::uuid, $2::message_role, $3, $4::jsonb, $5, NOW())
        RETURNING id::text
        """,
        conversation_id,
        role,
        content,
        blocks_json,
        tokens_used,
    )
    message_id: str = row["id"]

    await touch_conversation(conversation_id)

    logger.debug("Appended message: %s role=%s conversation=%s", message_id, role, conversation_id)
    return message_id


async def delete_conversation(session_id: str, user_id: str) -> bool:
    pool = get_pool()
    result = await pool.execute(
        """
        WITH deleted AS (
            DELETE FROM messages
            WHERE conversation_id = (
                SELECT id FROM conversations
                WHERE session_id = $1::uuid AND user_id = $2::uuid
            )
        )
        DELETE FROM conversations
        WHERE session_id = $1::uuid AND user_id = $2::uuid
        """,
        session_id,
        user_id,
    )
    deleted = result != "DELETE 0"
    if deleted:
        logger.info("Deleted conversation: session=%s user=%s", session_id, user_id)
    else:
        logger.warning("Conversation not found for delete: session=%s user=%s", session_id, user_id)
    return deleted


async def load_message_history(
    conversation_id: str,
    limit: int,
) -> list[dict[str, Any]]:
    import json

    pool = get_pool()
    rows = await pool.fetch(
        """
        SELECT
            id::text,
            role::text,
            content,
            blocks,
            tokens_used,
            created_at
        FROM messages
        WHERE conversation_id = $1::uuid
          AND role IN ('user', 'assistant')
        ORDER BY created_at DESC
        LIMIT $2
        """,
        conversation_id,
        limit,
    )

    messages = []
    for row in reversed(rows):
        record = dict(row)
        if record["blocks"] and isinstance(record["blocks"], str):
            record["blocks"] = json.loads(record["blocks"])
        messages.append(record)

    return messages
